services:
  - type: web
    name: safar-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_NAME
        value: Safar API
      - key: ENVIRONMENT
        value: production
      - key: API_CORS_ORIGINS
        value: '["*"]'
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: SUPABASE_JWT_AUDIENCE
        value: authenticated
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_FOLDER
        value: safar
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_TEXT_MODEL
        value: gemini-flash-latest
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_TEXT_MODEL
        value: llama-3.1-8b-instant
